name: pbcs_bible_course
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  fluttertoast: ^8.2.1
  firebase_database: ^10.1.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
  - assets/logo.png
  - assets/sun_logo.png
  #   - images/a_dot_ham.jpeg

 

  fonts:
    - family: Jameel Noori Nastaleeq Kasheeda
      fonts:
        - asset: assets/fonts/Jameel Noori Nastaleeq Kasheeda.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

