name: pbcs_bible_course
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.10.3'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_storage: ^11.2.2
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  fluttertoast: ^8.2.2
  firebase_database: ^10.2.2
  provider: ^6.0.5
  file_picker: ^4.6.1
  audioplayers: ^4.1.0
  just_audio: ^0.9.34
  flutter_pdfview: ^1.3.1
  flutter_cache_manager: ^3.3.0
  flutter_quill: ^7.2.1
  
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
  - assets/logo.png
  - assets/sun_logo.png
  - assets/courses.png
  - assets/quiz.png
  - assets/analytics.png
  #   - images/a_dot_ham.jpeg

 

  fonts:
    - family: Jameel Noori Nastaleeq Kasheeda
      fonts:
        - asset: assets/fonts/Jameel Noori Nastaleeq Kasheeda.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Gulzar-Regular
      fonts:
        - asset: assets/fonts/Gulzar-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

